apiVersion: v1
kind: Secret
metadata:
    name: github-user-pass
    annotations:
        build.knative.dev/git-0: https://github.wdf.sap.corp
type: kubernetes.io/basic-auth
data:
    # Use 'echo -n "username" | base64' to generate this string
    username: aTAzMzA4NQ==
    # Use 'echo -n "password" | base64' to generate this string
    password: VGVsbmV0MTIzIw==